spring.application.name=ayanami
spring.data.redis.host=localhost
spring.data.redis.port=7000
spring.data.redis.password=123456
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.datasource.url=jdbc:mysql://localhost:3306/trip_assistant?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

dify.base-url=http://localhost/v1
dify.api.key=app-fuK3Rz2w8yp6Qpf4WevkOcWB
dify.app-id=6b6d842d-29b5-4aa3-9a66-51c0eb431d58
dify.api.url=http://localhost/v1/chat-messages
server.port=8080
