spring.application.name=ayanami

# Dify API ??
dify.base-url=http://localhost/v1
dify.api-key=app-XfqBr5mYuaYZX8BykTZz2U7M
dify.app-id=de30ad3b-0870-4b06-90ce-0011401ff66c
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
